config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get 'articles_tags/:tag', to: 'articles#index', as: :articles_tag
    get 'books_tags/:tag', to: 'books#index', as: :books_tag
    get '/pages/*id' => 'pages#show', as: :page, format: false

    devise_for :users, path_names: {
                         sign_up: 'register',
                         sign_in: 'log_in',
                         sign_out: 'log_out'
                     }
    resources :books do
      resources :comments
    end
    resources :articles do
      resources :comments
    end
    resources :roles
  end
  get 'sitemap' => 'welcome#sitemap'
  get 'feed', to: 'welcome#feed', format: 'rss'
  get 'robots' => 'welcome#robots', format: :text

  root 'articles#index'

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id                 :integer          not null, primary key
#  title              :string
#  content            :text
#  pub_date           :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  show               :boolean
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  preview            :text
#

class Article < ActiveRecord::Base
  has_many :comments, as: :commentable, inverse_of: :commentable
  # PAPERCLIP_STORAGE_OPTS defined in config/enviroment/development\production.rb
  has_attached_file :image, PAPERCLIP_STORAGE_OPTS

  acts_as_taggable # act as taggable не должно быть точек
  acts_as_taggable_on :tags_for_articles
  translates :title, :content, :preview, fallbacks_for_empty_translations: true
  accepts_nested_attributes_for :translations, allow_destroy: true

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/gif', 'image/png'] }
  validates :image, attachment_presence: true
  validates :title, length: { maximum: 140, minimum: 1 }
  validates :content, :pub_date, :preview, :tags_for_article_list, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # TODO: Добавить счётчик комментариев и просмотров к статьям
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :load_tags, only: [:index]

  respond_to :html

  load_and_authorize_resource
  def index
    @article_decorators = load_articles.map { |article| ArticleDecorator.new(article, view_context) }
  end

  def show
    @comments = @article.comments.order('created_at DESC')
    @comment = Comment.new
    @article_decorator = ArticleDecorator.new(@article, view_context)
  end

  def new
    respond_with(@article = Article.new)
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    @article.tags_for_article_list.add(params[:tags_for_article_list], parse: true)
    @article.save
    respond_with(@article)
  end

  def update # TODO: проверка параметра в пост запросе :show - только для админа
    @article.tags_for_article_list.add(params[:tags_for_article_list], parse: true)
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: t('.article_updated') }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: t('.article_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :preview, :content, :pub_date, :show, :image, :tags_for_article_list)
  end

  def load_tags
    @tags = Article.tag_counts_on :tags_for_articles
  end

  def load_articles
    if user_signed_in?
      return @articles = Article.tagged_with(params[:tag]).order('pub_date DESC').page(params[:page]).per(5) if params[:tag]
      @articles = Article.order('pub_date DESC').page(params[:page]).per(5)
    else
      return @articles = Article.tagged_with(params[:tag]).where(show: true).order('pub_date DESC').page(params[:page]).per(5) if params[:tag]
      @articles = Article.where(show: true).order('pub_date DESC').page(params[:page]).per(5)
    end
  end
end

app/views/articles/_article_preview.html.slim
h3.blog-post-title
  = article_decorator.title_link
p.blog-post-meta
  |   #{t(:tags)}:
  |   #{article_decorator.show_article_tags}
= image_tag article_decorator.image_original, class: 'img-responsive img-thumbnail article-img', alt: "#{article_decorator.title}"
.collapse.in id="preview-article-#{article_decorator.id}" data-toggle='collapse'
  = article_decorator.preview
  .clearfix
  a.btn.pull-right.show_full_article data-article-id="#{article_decorator.id}" data-toggle='collapse' data-target="#article-collapse-#{article_decorator.id}"
    = fa_icon 'eye'
    '
    = t(:show_full_article)
.collapse id="article-collapse-#{article_decorator.id}" data-toggle='collapse'
  = article_decorator.content
  .collapse id="article-comments-collapse-#{article_decorator.id}" data-toggle='collapse'
    = render partial: "comments/disqus_comments", locals: {obj: article_decorator}
  a.btn.pull-right.show_full_article data-article-id="#{article_decorator.id}" data-toggle='collapse' data-target="#article-collapse-#{article_decorator.id}"
    = fa_icon 'eye-slash'
    '
    | #{t(:show_preview_article)}
= link_to article_path(article_decorator.id), class: 'btn pull-right' do
  = fa_icon 'comment-o'
  '
  = t('comments.new.new_comment')
.clearfix
= article_decorator.small_update_btn
'
= article_decorator.small_destroy_btn
hr

app/views/articles/_form.html.slim
= form_for(@article, html: { :multipart => true, class: 'form-horizontal'}) do |f|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        |  prohibited this article from being saved:
      ul
        - @article.errors.full_messages.each do |message|
          li= message
  .form-group
    = f.label Article.human_attribute_name(:title), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control', maxlength: 140
  .form-group
    = f.label t('articles.index.tags_for_article_list'), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :tags_for_article_list, class: 'form-control', value: @article.tags_for_article_list.to_s
  .form-group
    = f.label Article.human_attribute_name(:image), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.file_field :image
  .form-group
    = f.label Article.human_attribute_name(:preview), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.cktext_area :preview, class: 'form-control',:ckeditor => {:language => 'ru'}
  .form-group
    = f.label Article.human_attribute_name(:content), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.cktext_area :content, class: 'form-control',:ckeditor => {:language => 'ru'}
  .form-group
    = f.label Article.human_attribute_name(:pub_date), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.datetime_select :pub_date, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
        label
          = f.check_box :show
          = t('pub_now')
  .form-group
    .actions.col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/articles/edit.html.slim
h1 Editing Article
= render 'form'
= link_to t('show'), @article, class: 'btn btn-default'
| \
= link_to 'Back', articles_path, class: 'btn btn-default'

app/views/articles/index.html.slim
- if notice
  .alert.alert-success.alert-dismissible role="alert"
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true"  ×
    = notice
.col-sm-8.blog-main
  h1= t('.listing_articles')
  hr
  = render 'application/adsense_article_top_adaptive'
  hr
  - @article_decorators.each do |article_decorator|
    = render partial: 'articles/article_preview', locals: { article_decorator: article_decorator }
    br/
    br/
    br/
  = paginate @articles
=render 'application/sidebar'

app/views/articles/new.html.slim
h1= t('.new_article')
= render 'form'
= link_to t('back'), articles_path, class: 'btn btn-default'

app/views/articles/show.html.slim
.col-sm-12.blog-main
  h1= @article_decorator.title
  = image_tag @article_decorator.image_original, class: 'img-responsive article-img', style: " margin: 20px auto;", alt: "#{@article_decorator.title}"
  = @article_decorator.content.html_safe if @article_decorator.content
  p.blog-post-meta
    | #{t(:tags)}:
    | &nbsp #{@article_decorator.show_article_tags}
  = render 'application/adsense_article_top_adaptive'
  hr/
  .col-xs-12
    h2= t('.article_comments')
    = render partial: 'comments/disqus_comments', locals: {obj: @article}
    = render partial: 'comments/comments', locals: { comments: @comments, commentable: @article }
    = render partial: 'comments/form', locals: { commentable: @article }
    hr/
  - if can? :edit, @article
    = link_to t('helpers.submit.article.update'), edit_article_path(@article), class: 'btn btn-warning'
    '
    /! todo locale BACK btn
  = link_to t('back'), articles_path, class: 'btn btn-default'