config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get 'articles_tags/:tag', to: 'articles#index', as: :articles_tag
    get 'books_tags/:tag', to: 'books#index', as: :books_tag
    get '/pages/*id' => 'pages#show', as: :page, format: false

    devise_for :users, path_names: {
                         sign_up: 'register',
                         sign_in: 'log_in',
                         sign_out: 'log_out'
                     }
    resources :books do
      resources :comments
    end
    resources :articles do
      resources :comments
    end
    resources :roles
  end
  get 'sitemap' => 'welcome#sitemap'
  get 'feed', to: 'welcome#feed', format: 'rss'
  get 'robots' => 'welcome#robots', format: :text

  root 'articles#index'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id                      :integer          not null, primary key
#  author                  :string
#  title                   :string
#  description             :text
#  draft                   :boolean
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  book_cover_file_name    :string
#  book_cover_content_type :string
#  book_cover_file_size    :integer
#  book_cover_updated_at   :datetime
#  user_id                 :integer
#

class Book < ActiveRecord::Base
  has_many :comments, as: :commentable, inverse_of: :commentable

  acts_as_taggable
  acts_as_taggable_on :tags_for_books
  translates :title, :author, :description, fallbacks_for_empty_translations: true
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_attached_file :book_cover, styles: { medium: '320x470#' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :book_cover, content_type: /\Aimage\/.*\Z/
  validates :book_cover, attachment_presence: true

  validates :title, length: { maximum: 160, minimum: 1 }
  validates :author, :description, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # TODO: Добавить счётчик комментариев и просмотров к книгам.
  # TODO: rename uploaded images
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :load_tags, only: [:show, :index]
  load_and_authorize_resource

  respond_to :html

  def index
    @books_decorator = load_books.map { |book| BookDecorator.new(book, view_context) }
  end

  def show
    @commentable = @book
    @comments = @commentable.comments.order('created_at DESC')
    @comment = Comment.new
    @book_decorator = BookDecorator.new(@commentable, view_context)
    respond_with(@book_decorator)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit; end

  def create
    @book = Book.new(book_params)
    @book.tags_for_book_list.add(params[:tags_for_book_list], parse: true)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private

  def load_tags
    @tags = Book.tag_counts_on :tags_for_books
  end

  def book_params
    params.require(:book).permit(:author, :title, :description, :draft, :book_cover, :tags_for_book_list)
  end

  def load_books
    if user_signed_in?
      return @books = Book.tagged_with(params[:tag]).order('updated_at DESC') if params[:tag]
      @books = Book.all.order('updated_at DESC')
    else
      return @books = Book.tagged_with(params[:tag]).where(draft: false).order('updated_at DESC')if params[:tag]
      @books = Book.all.where(draft: false).order('updated_at DESC')
    end
  end
end

app/views/books/_book_modal_view.html.slim
.modal.fade id="book-#{book_decorator.id}" tabindex="-1"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close.glyphicon.glyphicon-remove data-dismiss="modal" type="button"
        h3= book_decorator.link_to_book
        p.text-muted
          em= book_decorator.author
        p
          = t(:tags)
          | : #{book_decorator.show_book_tags}
      .modal-body
        div
          img.img-responsive.thumbnail.modal-image.pull-left.col-xs-6 alt="#{book_decorator.title}" src="#{book_decorator.cover_medium}" /
          = book_decorator.description.html_safe if book_decorator.description
      .modal-footer
        = link_to book_path(book_decorator.id), title: t(:show), class: 'btn btn-default' do
          = fa_icon 'eye'
          = raw "&nbsp"
          = t(:show)
        = raw "&nbsp"
        = book_decorator.small_update_btn
        = raw "&nbsp"
        = book_decorator.small_destroy_btn
        button.btn.btn-primary aria-hidden="true" data-dismiss="modal" type="button"  Close

app/views/books/_form.html.slim
= form_for(@book, html: { :multipart => true, class: 'form-horizontal'}) do |f|
  - if @book.errors.any?
    #error_explanation
      h2
        = pluralize(@book.errors.count, "error")
        |  prohibited this book from being saved:
      ul
        - @book.errors.full_messages.each do |message|
          li= message
  .form-group
    = f.label Book.human_attribute_name(:author), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :author, class: 'form-control', maxlength: 160
  .form-group
    = f.label Book.human_attribute_name(:book_cover), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.file_field :book_cover
  .form-group
    = f.label Book.human_attribute_name(:title), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control', maxlength: 160
  .form-group
    = f.label t('books.index.tags_for_book_list'), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :tags_for_book_list, class: 'form-control', value: @book.tags_for_book_list.to_s
  .form-group
    = f.label Book.human_attribute_name(:description), class: 'col-sm-2 control-label'
    .col-sm-10
      = f.cktext_area :description, class: 'form-control', maxlength: 160
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
        label
          = f.check_box :draft
          = Book.human_attribute_name(:draft)
  .form-group
    .actions.col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/books/edit.html.slim
h1= t('.editing_book')
= render 'form'
= link_to t('show'), @book, class: 'btn btn-default'
| \
= link_to t('back'), books_path, class: 'btn btn-default'

app/views/books/index.html.slim
.container
  h1= t('.listing_books')
  hr
  .col-sm-8
    .row
      ul.list-unstyled
        - @books_decorator.each do |book_decorator|
          li.thumbnail.col-sm-3.col-xs-5.book_li
            div
              = link_to "#book-#{book_decorator.id}", data: {toggle: "modal"}, title: t(:show) do
                img.img-responsive alt="#{book_decorator.title}" src="#{book_decorator.cover_medium}" /
              = link_to book_path(book_decorator.id), title: t(:show), class: 'btn btn-block' do
                .caption.text-center
                  = fa_icon 'eye'
                  = raw("&nbsp")
                  = t(:show)
  - @books_decorator.each do |book_decorator|
    /! Modals for books
    = render partial: 'books/book_modal_view', locals: {book_decorator: book_decorator}
  = render 'application/sidebar'

app/views/books/new.html.slim
h1= t('.new_book')
= render 'form'
= link_to t('back'), books_path, class: 'btn btn-default'

app/views/books/show.html.slim
.col-xs-12.col-sm-6
  = image_tag @book_decorator.book_cover, class: 'img-responsive'
.col-xs-12.col-sm-6
  p
    strong= @book_decorator.author
  p
    strong= @book_decorator.title
  p
    = raw @book_decorator.description
  p.blog-post-meta
    | #{t(:tags)}:
    | #{@book_decorator.show_book_tags}
  = @book_decorator.small_update_btn
  = @book_decorator.small_destroy_btn
  = link_to t('back'), books_path, class: 'btn btn-default'
.col-xs-12
  hr
  h2= t('.book_comments')
  #disqus_thread
  javascript:
    var disqus_config = function () {
      this.page.url = "#{books_url(@book_decorator.id)}";  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = "book-#{@book_decorator.id}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = '//badalloff-ninja.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  = render partial: 'comments/comments', locals: { comments: @comments, commentable: @commentable }
  = render partial: 'comments/form', locals: { commentable: @commentable }