config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get 'articles_tags/:tag', to: 'articles#index', as: :articles_tag
    get 'books_tags/:tag', to: 'books#index', as: :books_tag
    get '/pages/*id' => 'pages#show', as: :page, format: false

    devise_for :users, path_names: {
                         sign_up: 'register',
                         sign_in: 'log_in',
                         sign_out: 'log_out'
                     }
    resources :books do
      resources :comments
    end
    resources :articles do
      resources :comments
    end
    resources :roles
  end
  get 'sitemap' => 'welcome#sitemap'
  get 'feed', to: 'welcome#feed', format: 'rss'
  get 'robots' => 'welcome#robots', format: :text

  root 'articles#index'

end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Role < ActiveRecord::Base
  has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit; end

  def create
    @role = Role.new(role_params)
    @role.save
    respond_with(@role)
  end

  def update
    @role.update(role_params)
    respond_with(@role)
  end

  def destroy
    @role.destroy
    respond_with(@role)
  end

  private
  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name, :description)
  end
end

app/views/roles/_form.html.slim
= form_for(@role) do |f|
  - if @role.errors.any?
    #error_explanation
      h2
        = pluralize(@role.errors.count, "error")
        | prohibited this role from being saved:
      ul
        - @role.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :name
    br/
    = f.text_field :name
  .field
    = f.label :description
    br/
    = f.text_field :description
  .actions
    = f.submit

app/views/roles/edit.html.slim
h1 Editing Role
= render 'form'
= link_to 'Show', @role
| \
= link_to 'Back', roles_path

app/views/roles/index.html.slim
h1 Listing Roles
table
  thead
    tr
      th Name
      th Description
      th colspan="3" 
  tbody
    - @roles.each do |role|
      tr
        td= role.name
        td= role.description
        td= link_to 'Show', role
        td= link_to 'Edit', edit_role_path(role)
        td= link_to 'Destroy', role, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New Role', new_role_path

app/views/roles/new.html.slim
h1 New Role
= render 'form'
= link_to 'Back', roles_path

app/views/roles/show.html.slim
p
  strong Name:
  = @role.name
p
  strong Description:
  = @role.description
= link_to 'Edit', edit_role_path(@role)
| \
= link_to 'Back', roles_path