config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get 'articles_tags/:tag', to: 'articles#index', as: :articles_tag
    get 'books_tags/:tag', to: 'books#index', as: :books_tag
    get '/pages/*id' => 'pages#show', as: :page, format: false

    devise_for :users, path_names: {
                         sign_up: 'register',
                         sign_in: 'log_in',
                         sign_out: 'log_out'
                     }
    resources :books do
      resources :comments
    end
    resources :articles do
      resources :comments
    end
    resources :roles
  end
  get 'sitemap' => 'welcome#sitemap'
  get 'feed', to: 'welcome#feed', format: 'rss'
  get 'robots' => 'welcome#robots', format: :text

  root 'articles#index'

end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  before_filter :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  self.responder = ApplicationResponder
  respond_to :html

  # cancancan Handle Unauthorized Access
  rescue_from CanCan::AccessDenied do |exception|
    begin
      redirect_to :back, notice: exception.message
    rescue ActionController::RedirectBackError
      redirect_to main_app.root_path, alert: exception.message
    end
  end

  private

  def set_locale
    if params[:locale].present?
      if I18n.available_locales.include?(params[:locale].to_sym)
        I18n.locale = params[:locale]
      else
        flash[:notice] = "#{params[:locale]} translation not available"
        logger.error flash[:notice]
      end
    elsif
      request.env['HTTP_ACCEPT_LANGUAGE'] == 'ru'
      I18n.locale = 'ru'
    end
    # Можно использовать для установленных пользователем языков в настройках Аккаунта
    # current_user.locale
    # request.env["HTTP_ACCEPT_LANGUAGE"]
  end

  def default_url_options(options = {})
    { locale: I18n.locale }
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_MSG = {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def bootstrap_icon_for flash_type
    { success: 'ok-circle', error: 'remove-circle', alert: 'warning-sign', notice: 'exclamation-sign' }[flash_type.to_sym] || 'question-sign'
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat content_tag(:i, nil, class: "glyphicon glyphicon-#{bootstrap_icon_for(msg_type)}")
               concat ' '
               concat message
             end)
    end
    nil
  end
end

app/views/application/_adsense_article_top_adaptive.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- articles top Adaptive -->
<ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-5677662134676433"
  data-ad-slot="2045367597"
  data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/application/_adsense_sidebar_adaptive.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- sidebar-block -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="5253331190"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/application/_footer.html.slim
br/
br/
footer.blog-footer
  p
    | Blog template built for
    a href="http://getbootstrap.com"  Bootstrap
    | by
    a href="https://twitter.com/mdo"  @mdo
    | and
    a href=root_path  me
  p
    a.btn.btn-default href="#"  Back to top
  .btn-group role="group" 
    = link_to 'RSS', feed_path, class: 'btn btn-warning'
    - if user_signed_in?
      = link_to t('sign_out'), destroy_user_session_path, method: :delete, class: 'btn btn-danger'
      = link_to t('edit_user'), edit_user_registration_path, class: 'btn btn-default'
    - else
      = link_to t('sign_in'), new_user_session_path, class: 'btn btn-info'
    = link_to 'Sitemap.xml', '/sitemap.xml', class: 'btn btn-default'
= render 'application/ga' unless user_signed_in?

app/views/application/_ga.html.slim
//javascript:
//  | (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
//    | (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
//          | m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
//  | })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
//
//  | ga('create', 'UA-63489618-1', 'auto');
//  | ga('send', 'pageview');

script[async src = "https://www.googletagmanager.com/gtag/js?id=UA-63489618-1"]
script
  | window.dataLayer = window.dataLayer || [];function gtag() {dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'UA-63489618-1');

app/views/application/_head_menu.html.slim
nav.navbar.navbar-default.navbar-fixed-top.blog-masthead
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target="#header-menu" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Badalloff.science', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse.navbar-right id='header-menu'
      ul.nav.navbar-nav
        li= link_to t('articles_link'), articles_path, class: 'blog-header-nav-item'
        li= link_to t('books_link'), books_path, class: 'blog-header-nav-item'
        /li= link_to t('about_me_link'), page_path('about_me'), class: 'blog-header-nav-item'
      form.navbar-form.navbar-right role=""
        = link_to_unless_current("<img src='/flags/en_14.png'> En".html_safe, { locale: 'en' }, { class: 'btn btn-info' }) do \
            link_to("<img src='/flags/ru_14.png'> Ru".html_safe, { locale: 'ru' }, { class: 'btn btn-info' })                 \
          end
    .navbar-collapse
  .container-fluid

app/views/application/_sidebar.html.slim
.col-sm-3.col-sm-offset-1.blog-sidebar
  /! About section
  .sidebar-module.sidebar-module-inset
    h4= t('about')
    p= t('follow_links').html_safe
  .sidebar-module
    h4= t('elsewhere')
    ol.list-unstyled
      li
        a href="https://www.facebook.com/badalloff" target="_blank"
          = fa_icon 'facebook-official'
          | Facebook
        '
        = t('facebook').html_safe
      li
        a href="https://github.com/BadAllOff" target="_blank"
          = fa_icon 'github-square'
          | GitHub
      li
        a href="https://www.linkedin.com/in/shamilbadalloff/" target="_blank"
          = fa_icon 'linkedin-square'
          | LinkedIn
        '
        = t('linkedin').html_safe
      li
        a href="https://twitter.com/ShamilBadalov" target="_blank"
          = fa_icon 'twitter-square'
          | Twitter
  .sidebar-module
    = render 'application/adsense_sidebar_adaptive'
  .sidebar-module
    h4= t('tags')
    .tags-box
      - if controller_name == 'books'
        - tag_cloud (@tags), %w[btn-xs btn-sm btn btn-lg] do |tag, css_class|
            = link_to books_tag_path(tag.name), class: "#{css_class} btn btn-info pull-left" do
              = "#{tag.name} "
              span.badge= tag.taggings_count
      - else
        - tag_cloud (@tags), %w[btn-xs btn-sm btn btn-lg] do |tag, css_class|
          = link_to articles_tag_path(tag.name), class: "#{css_class} btn btn-info pull-left" do
            = "#{tag.name} "
            span.badge= tag.taggings_count

app/views/application/adsense_article_top_adaptive.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- articles top Adaptive -->
<ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-5677662134676433"
  data-ad-slot="2045367597"
  data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>